services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/java:1-11-bullseye
    env_file:
      - ./.env
    volumes:
      - ${WORKSPACE}:/workspace:cached
      - ./certs:/usr/local/share/ca-certificates/
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 
    
networks:
  default:
    name: $NETWORK