services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/java:1-11-bullseye
    volumes:
      - ../../pokeapp:/workspace:cached
    env_file:
      - ./.env
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 
    
networks:
  default:
    name: $NETWORK